import { Archive, Ban, Check, Plus, RotateCcw, Save, Trash2, X } from 'lucide-react'
import { type FormEvent, type ReactNode, useEffect, useState } from 'react'

import { TagField, TypeScopeFields } from '@/components/memory-fields'
import { Hint, Label, MetaTile } from '@/components/workbench-primitives'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Textarea } from '@/components/ui/textarea'
import { formatDate } from '@/lib/memory-view'
import { conceptHints } from '@/lib/ui-copy'
import type { Memory, MemoryAction } from '@/types'

export function MemoryModal({
  children,
  eyebrow,
  open,
  onClose,
  title,
}: {
  children: ReactNode
  eyebrow: string
  open: boolean
  onClose: () => void
  title: string
}) {
  useEffect(() => {
    if (!open) return

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose()
    }

    document.addEventListener('keydown', onKeyDown)
    return () => document.removeEventListener('keydown', onKeyDown)
  }, [onClose, open])

  if (!open) return null

  return (
    <div
      className="fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm"
      role="presentation"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) onClose()
      }}
    >
      <section
        aria-modal="true"
        className="flex max-h-[calc(100vh-2rem)] w-[min(48rem,calc(100vw-2rem))] flex-col overflow-hidden rounded-md border border-border bg-card shadow-2xl"
        role="dialog"
      >
        <div className="flex items-start justify-between gap-3 border-b border-border px-4 py-3">
          <div className="min-w-0">
            <p className="text-sm font-semibold uppercase tracking-widest text-muted-foreground">
              {eyebrow}
            </p>
            <h2 className="mt-1 truncate text-lg font-semibold text-foreground">{title}</h2>
          </div>
          <Hint label="Close this memory detail modal.">
            <Button
              aria-label="Close memory detail"
              size="icon"
              variant="outline"
              onClick={onClose}
            >
              <X />
            </Button>
          </Hint>
        </div>
        <ScrollArea className="min-h-0 flex-1">
          <div className="p-4">{children}</div>
        </ScrollArea>
      </section>
    </div>
  )
}

export function CreateForm({
  onCreate,
}: {
  onCreate: (event: FormEvent<HTMLFormElement>) => void
}) {
  const [tags, setTags] = useState('')

  return (
    <form className="grid gap-4" onSubmit={onCreate}>
      <TypeScopeFields type="knowledge" />
      <Label text="Display title">
        <Input
          className="border-border bg-background/60 text-foreground"
          name="title"
          placeholder="Short title generated by your AI agent or written by you"
        />
      </Label>
      <TagField tags={tags} onTagsChange={setTags} />
      <Label text="Memory">
        <Textarea
          className="min-h-56 border-border bg-background/60 text-foreground"
          name="content"
          placeholder="Write a concise, durable memory..."
          required
        />
      </Label>
      <Button className="w-fit" type="submit">
        <Plus />
        Create memory
      </Button>
    </form>
  )
}

export function Editor({
  memory,
  onAction,
  onUpdate,
}: {
  memory: Memory
  onAction: (action: MemoryAction) => void
  onUpdate: (event: FormEvent<HTMLFormElement>) => void
}) {
  const isProposed = memory.metadata.status === 'proposed'
  const isArchived = memory.metadata.status === 'archived'
  const isDeleted = memory.metadata.status === 'deleted'
  const isNoise = memory.metadata.status === 'noise'
  const canEdit = !isProposed && !isArchived && !isDeleted && !isNoise
  const [tags, setTags] = useState(memory.metadata.tags.join(', '))
  const [dangerOpen, setDangerOpen] = useState(false)

  useEffect(() => {
    setTags(memory.metadata.tags.join(', '))
  }, [memory.metadata.id, memory.metadata.tags])

  return (
    <form className="grid gap-4" onSubmit={onUpdate}>
      <div className="grid grid-cols-2 gap-2 max-md:grid-cols-1">
        <MetaTile label="Status" value={memory.metadata.status} />
        <MetaTile label="Updated" value={formatDate(memory.metadata.updated_at)} />
      </div>
      <TypeScopeFields disabled={!canEdit} type={memory.metadata.type} />
      <Label text="Display title">
        <Input
          className="border-border bg-background/60 text-foreground"
          defaultValue={memory.metadata.title ?? ''}
          disabled={!canEdit}
          name="title"
          placeholder="Optional short title"
        />
      </Label>
      <TagField disabled={!canEdit} tags={tags} onTagsChange={setTags} />
      <Label text="Memory">
        <Textarea
          className="min-h-72 border-border bg-background/60 text-foreground"
          defaultValue={memory.content}
          name="content"
          readOnly={!canEdit}
          required
        />
      </Label>

      {isProposed ? (
        <div className="flex flex-wrap gap-2">
          <Hint label={conceptHints.approve}>
            <Button type="button" onClick={() => onAction('approve')}>
              <Check />
              Approve
            </Button>
          </Hint>
          <Hint label={conceptHints.reject}>
            <Button type="button" variant="destructive" onClick={() => onAction('reject')}>
              <X />
              Reject
            </Button>
          </Hint>
        </div>
      ) : (
        <div className="grid gap-3">
          <div className="flex flex-wrap gap-2">
            {canEdit ? (
              <>
                <Hint label={conceptHints.save}>
                  <Button type="submit">
                    <Save />
                    Save
                  </Button>
                </Hint>
                <Hint label={conceptHints.archive}>
                  <Button type="button" variant="outline" onClick={() => onAction('archive')}>
                    <Archive />
                    Archive
                  </Button>
                </Hint>
                <Hint label={conceptHints.markNoise}>
                  <Button type="button" variant="outline" onClick={() => onAction('mark-noise')}>
                    <Ban />
                    Mark noise
                  </Button>
                </Hint>
              </>
            ) : null}
            {isArchived || isDeleted || isNoise ? (
              <Hint label={conceptHints.restore}>
                <Button type="button" onClick={() => onAction('restore')}>
                  <RotateCcw />
                  Restore
                </Button>
              </Hint>
            ) : null}
          </div>
          <div className="rounded-md border border-destructive/25 bg-destructive/10 p-3">
            <button
              className="flex items-center gap-2 text-sm font-medium text-destructive"
              type="button"
              onClick={() => setDangerOpen(!dangerOpen)}
            >
              <Trash2 className="size-4" />
              Delete actions
            </button>
            {dangerOpen ? (
              <div className="mt-3 flex flex-wrap gap-2">
                <Hint label={conceptHints.softDelete}>
                  <Button type="button" variant="outline" onClick={() => onAction('delete')}>
                    <Trash2 />
                    Soft delete
                  </Button>
                </Hint>
                <Hint label={conceptHints.physicalDelete}>
                  <Button
                    type="button"
                    variant="destructive"
                    onClick={() => onAction('physical-delete')}
                  >
                    <Trash2 />
                    Confirm physical delete
                  </Button>
                </Hint>
              </div>
            ) : null}
          </div>
        </div>
      )}
    </form>
  )
}
